### PR TITLE
Update examples to PHP >= 5.4 Strict standarts

### PR DESCRIPTION
**Pull request by skad0**
If you are using PHP >= 5.4 you should define which Model used as a parameter, either you will get exception.

### CODE REVIEW

**Comment by themsaid** [comment]
@skad0 hello there, I'm not sure if I understand what this PR is for? I'm a bit confused, the methods should be public cause they're called from within `AbstractTransformer::transform()` in case the given first argument is a collection. Making it private will cause this behaviour to fail.

**Comment by skad0** [comment]
@themsaid it isn't main issue, but here i use protected, not private. This method calls from `AbstractTransformer` and our custom transformer will extend it, and that will be OK.
Main issue is about php [incompatible changes](http://php.net/manual/en/migration54.incompatible.php).
If you don't define which model we expect we will get PHP Strict standards Exception.

**Comment by themsaid** [comment]
What do you mean by "don't define which model"? can you show an example by code that will throw an exception?

**Comment by skad0** [comment]
@themsaid 

```

class TaskTransformer extends AbstractTransformer
{
    protected function transformModel(Model $item)
    {
        // some code

        return $output;
    }
}
```

If we add use statement - it'll be OK.

```
use Themsaid\Transformers\AbstractTransformer;
use Illuminate\Database\Eloquent\Model;
```

**Pull request merged**
